apiVersion: apps/v1
kind: Deployment
metadata:
  name: pf-frontend-staging
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment-name: pf-frontend-staging
  template:
    metadata:
      labels:
        deployment-name: pf-frontend-staging
    spec:
      containers:
        - name: pf-frontend-staging
          image: b8it131reg2.azurecr.io/pf-frontend-staging
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: pf-frontend-loadbalancer-staging
  name: pf-frontend-loadbalancer-staging
spec:
  type: LoadBalancer
  ports:
    - name: pf-frontend-loadbalancer-service-port-staging
      port: 80
      targetPort: 80
      protocol: TCP 
  selector:
    deployment-name: pf-frontend-loadbalancer-staging
---
apiVersion: v1
kind: Service
metadata:
  labels:
    service-label: pf-frontend-cluster-service-staging
  name: pf-frontend-cluster-service-staging
spec:
  type: ClusterIP
  ports:
    - name: pf-frontend-cluster-service-port-staging
      port: 80
  selector:
    deployment-name: pf-frontend-cluster-service-staging
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: pf-frontend-staging-hpa
spec:
  maxReplicas: 4
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pf-frontend-staging
  targetCPUUtilizationPercentage: 60